# FROM openjdk:8-jdk-alpine
# EXPOSE 1097
# VOLUME /tmp
# RUN apk update
# RUN apk add --no-cache fontconfig ttf-dejavu
# RUN apk --update --no-cache add busybox-extras
# COPY target/loizRmiClient.jar target/loizRmiClient.jar
# COPY java.policy ${JAVA_HOME}/lib/security/java.policy
# CMD tail -f /dev/null
# ENTRYPOINT ["java","-Djava.rmi.server.hostname=192.168.6.107", "-jar", "target/loizRmiClient.jar"]
# ENTRYPOINT ["java", "-jar", "target/loizRmiClient.jar"]

version: "3.3"

services:
  myservicename:
    image: openjdk:8-jdk-alpine
    container_name: mycontainername
    ports:
      - 1097:1097
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - /target/
      - ./target/loizRmiClient.jar:/target/loizRmiClient.jar
    environment:
      - NOM:'TOTO'
	  - DISPLAY: ${DISPLAY}
    entrypoint: ["sh", "-c", "tail -f /dev/null"]
#   entrypoint:[ 'java', '-jar', 'target/loizRmiClient.jar']