version: "3.3"

services:
  myservicename:
    image: openjdk:8-jdk-alpine
    container_name: mycontainername
    hostname: 192.168.6.107
#    ports:
#      - "1097:1097"
    build: 
     dockerfile: DockerfileForCompose
    volumes:
     - ./java.policy:/${JAVA_HOME}/jre/lib/security/java.policy
     - ~/.Xauthority:/root/.Xauthority:rw
     - /tmp/.X11-unix
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /opt/X11
     - /opt/X11:/opt/X11
     - /dev
     - /dev:/dev
     - /target/
     - ./target/loizRmiClient.jar:/target/loizRmiClient.jar
 #   - ./java.policy:/target/java.policy
    network_mode: host
    environment:
     - NOM='TOTO'
     - DISPLAY=192.168.6.107:0  
    entrypoint: ["sh", "-c", "tail -f /dev/null"] 
#   entrypoint: ["java","-Dsun.java2d.xrender=false","-Djava.rmi.server.hostname=192.168.6.107","-Dcom.sun.management.jmxremote=false", "-Dcom.sun.management.jmxremote.port=1097", "-Dcom.sun.management.jmxremote.authenticate=false", "-Dcom.sun.management.jmxremote.ssl=false", "-Dcom.sun.management.jmxremote.rmi.port=1097", "-jar", "target/loizRmiClient.jar"]
#   entrypoint: ["java","-Djava.rmi.server.hostname=192.168.6.107", "-Dsun.java2d.xrender=false", "-jar", "target/loizRmiClient.jar"]
#   entrypoint: ["sh", "-c", "tail -f /dev/null"]
