FROM openjdk:8-jdk-alpine
EXPOSE 1097
VOLUME /tmp
COPY target/LoizRmiServer.jar target/LoizRmiServer.jar
ENTRYPOINT ["java", "-Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=1097 -Dcom.sun.management.jmxremote.rmi.port=1097 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=true", "-jar", "target/LoizRmiServer.jar"]

